# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [9]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [25]:
### [your code here]
print(np.__version__)
np.show_config()


1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/katyd/anaconda3/Library/include
    lib directory: C:/Users/katyd/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [36]:
### [your code here]
a = np.random.rand(2, 3, 5)  # Generation of a 2x3x5 3D array with random values

print(a.shape)  # test output - expected (2,3,4)


(2, 3, 5)



### 4. Print a.


In [30]:
### [your code here]
print(a) # Test the random values

[[[0.3657966  0.90109664 0.86953173 0.56046572 0.52880806]
  [0.28327227 0.70052352 0.69911563 0.38725705 0.63597503]
  [0.09208286 0.31723135 0.34864698 0.96194109 0.01394564]]

 [[0.68390547 0.08867544 0.52529695 0.83460172 0.56708027]
  [0.63723314 0.18687267 0.34646646 0.18628825 0.24468392]
  [0.64204977 0.12436984 0.87679126 0.98289078 0.7844196 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [ ]:
### [your code here]
b = np.ones((5, 2, 3)) 




### 6. Print b.


In [34]:
### [your code here]
print(b.shape)  # (5, 2, 3)
print(b)


(5, 2, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [37]:
### [your code here]
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)

print("Same shape?", a.shape == b.shape)
print("Same size?", a.size == b.size)


Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)
Same shape? False
Same size? True



### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]
result = a + b # no they have not the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [47]:
### [your code here]
a = np.random.rand(2, 3, 5) 
b = np.ones((5, 2, 3)) 

c = b.transpose(1, 2, 0)  # Now c.shape = (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [43]:
### [your code here]
d = a + c
print(d.shape)  # (2, 3, 5)


(2, 3, 5)



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [48]:
### [your code here]
print("Array a:\n", a)
print("\nArray d (a + c):\n", d)



Array a:
 [[[0.7572231  0.18780504 0.38957816 0.85835148 0.40658923]
  [0.62407291 0.69618725 0.40103061 0.92771998 0.22542756]
  [0.68288134 0.48501065 0.7842375  0.04488339 0.98324777]]

 [[0.58894603 0.84870154 0.73658104 0.23794881 0.21809411]
  [0.57306364 0.83240538 0.29737822 0.10364769 0.19825208]
  [0.96656248 0.1943725  0.62006074 0.55945795 0.04527458]]]

Array d (a + c):
 [[[1.85212586 1.45014747 1.79032935 1.73556085 1.2810904 ]
  [1.77530255 1.67697815 1.51651305 1.89625968 1.63087982]
  [1.11891017 1.25211444 1.19646734 1.29839114 1.75313791]]

 [[1.40337783 1.64615612 1.68358535 1.34594564 1.1483694 ]
  [1.72406366 1.3151092  1.43978664 1.51793071 1.54598   ]
  [1.44762445 1.19714572 1.25084346 1.85281363 1.65647785]]]



### 12. Multiply a and c. Assign the result to e.


In [49]:
### [your code here]
e = a * c
print("Array e (a * c):\n", e)


Array e (a * c):
 [[[0.7572231  0.18780504 0.38957816 0.85835148 0.40658923]
  [0.62407291 0.69618725 0.40103061 0.92771998 0.22542756]
  [0.68288134 0.48501065 0.7842375  0.04488339 0.98324777]]

 [[0.58894603 0.84870154 0.73658104 0.23794881 0.21809411]
  [0.57306364 0.83240538 0.29737822 0.10364769 0.19825208]
  [0.96656248 0.1943725  0.62006074 0.55945795 0.04527458]]]




### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]
result = e = a # yes no error message






### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [ ]:
### [your code here]
d = a + c
print(d.shape)  # (2, 3, 5)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [52]:
### [your code here]
f = np.empty(d.shape, dtype=str)  #d exists and has shape (2, 3, 5)






### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [54]:
### [your code here]
import numpy as np

# Assuming d exists and f was created previously
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

f = np.empty(d.shape, dtype=int)

f[d == d_min] = 0
f[d == d_max] = 100
f[d == d_mean] = 50
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [55]:
### [your code here]
import numpy as np

# Example: create d (2x3x5 random numbers)
d = np.random.random((2, 3, 5))

# Calculate statistics
d_min = d.min()
d_max = d.max()
d_mean = d.mean()

# Create empty f array with same shape
f = np.empty(d.shape)

# Apply conditions
f[d == d_min] = 0
f[d == d_max] = 100
f[d == d_mean] = 50
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75

# Print results
print("d:\n", d)
print("\nf:\n", f)



d:
 [[[0.63858838 0.97842368 0.73849151 0.4444369  0.36510092]
  [0.48798732 0.8826342  0.07737476 0.6345356  0.74559096]
  [0.82600639 0.53541003 0.66752199 0.65500488 0.7859179 ]]

 [[0.56170139 0.03870089 0.92617291 0.73729991 0.81432591]
  [0.90711578 0.47826598 0.04586168 0.95942183 0.62201317]
  [0.08204477 0.28645118 0.72030008 0.15962519 0.71368897]]]

f:
 [[[ 75. 100.  75.  25.  25.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.   0.  75.  75.  75.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  25.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [56]:
### [your code here]
import numpy as np

# Example array d
d = np.random.random((2, 3, 5))

# Calculate statistics
d_min, d_max, d_mean = d.min(), d.max(), d.mean()

# Create empty string array for f
f = np.empty(d.shape, dtype=str)

# Apply conditions for labeling
f[d == d_min] = "A"
f[d == d_max] = "E"
f[d == d_mean] = "C"
f[(d > d_min) & (d < d_mean)] = "B"
f[(d > d_mean) & (d < d_max)] = "D"

# Print result
print("d:\n", d)
print("\nf:\n", f)


d:
 [[[0.85330359 0.45046307 0.39179627 0.07448444 0.84613172]
  [0.12034524 0.10631957 0.31262006 0.09752211 0.88331082]
  [0.57809167 0.23105382 0.07915226 0.77671212 0.29982318]]

 [[0.12687171 0.63232444 0.08619222 0.8423109  0.00438713]
  [0.90293613 0.93339457 0.25658248 0.80219819 0.35201639]
  [0.74551317 0.33448287 0.71837158 0.39630745 0.59651861]]]

f:
 [[['D' 'B' 'B' 'B' 'D']
  ['B' 'B' 'B' 'B' 'D']
  ['D' 'B' 'B' 'D' 'B']]

 [['B' 'D' 'B' 'D' 'A']
  ['D' 'E' 'B' 'D' 'B']
  ['D' 'B' 'D' 'B' 'D']]]
